In [6]:
f = open("/Users/Jacob/Desktop/255/hw4/PCA_1024")
s = set()
for line in f:
    s.add(line.split('\t')[0][1:-1])

In [7]:
def inSet(s, string):
    if len(string) > 7: return
    if not string in s:
        print string
    inSet(s, string+'0')
    inSet(s, string+'1')

In [8]:
inSet(s, "")

0000001
0001000
010010
0100100
0100101
0110101
0110111
1101010


In [1]:
from RPTreePCA import RPTree
from RPTreePCA import RPNode
import pickle
import numpy as np

In [13]:
medians = pickle.load(open("/Users/Jacob/Desktop/255/hw4/rptree"))

In [15]:
tree = RPTree()
tree.read(medians)

In [50]:
data = []
for line in open("/Users/Jacob/Desktop/255/hw4/normalized_all.csv"):
    line = line.strip().split('\t')[1][1:-1]
    arr = [float(d) for d in line.split(",")]
    data.append(arr)
data = np.array(data)    

In [27]:
unitVecs = np.array(pickle.load(open("/Users/Jacob/Desktop/255/hw4/unitVecs", "rb")))

In [51]:
mapi = {}
for d in data:
    code = tree.encode(np.dot(unitVecs, d))
    if code in mapi:
        mapi[code] += 1
    else:
        mapi[code] = 1

In [52]:
len(mapi)

128

In [44]:
np.dot(unitVecs, data[0])

array([-0.21455982, -0.04887467, -1.76649446, -1.59824048,  0.85102346,
       -0.13575683, -0.89660139])

#### PCA of normalized_1024

In [20]:
data1024 = []
for line in open("/Users/Jacob/Desktop/255/hw4/normalized_all.csv"):
    line = line.strip().split('\t')[1][1:-1]
    arr = [float(d) for d in line.split(",")]
    data1024.append(arr)
data1024 = np.array(data1024)    

In [23]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
pca.fit(data1024)

PCA(copy=True, n_components=10, whiten=False)

In [24]:
pca.components_

array([[ 0.06621482,  0.0654548 ,  0.0658585 , ...,  0.00958088,
         0.00957642,  0.00973877],
       [-0.00970644, -0.01012571, -0.01043007, ...,  0.04045623,
         0.04124784,  0.04137731],
       [ 0.05393686,  0.05974241,  0.05987509, ..., -0.02962554,
        -0.03005097, -0.0306001 ],
       ..., 
       [ 0.00762351,  0.01961705,  0.03526644, ...,  0.00280327,
        -0.00210971, -0.01643899],
       [-0.04955206, -0.06513504, -0.07267573, ..., -0.01297607,
        -0.00495331, -0.00451196],
       [ 0.09507359,  0.12188836,  0.14410652, ...,  0.01854542,
         0.02133588,  0.04183416]])

In [29]:
pca.explained_variance_ratio_ 

array([ 0.26873376,  0.10435315,  0.03190656,  0.01964676,  0.01070293,
        0.00858634,  0.00784883,  0.00749013,  0.00659233,  0.00618548])

In [6]:
from Statistics2 import *

In [26]:
vec = VecStat(730)
for d in data1024:
    vec.accum(d)
result = vec.compute(10)

In [31]:
(countV,meanV)=vec.V.compute()

In [32]:
(countC,meanC)=vec.Cov.compute()

In [33]:
cov=meanC-outer(meanV,meanV)

In [34]:
(eigvalues,eigvectors)=linalg.eig(cov)

In [38]:
order=argsort(-abs(eigvalues))

In [39]:
eigvectors = eigvectors.transpose()
eigvectors=eigvectors[order]   # order eigenvectors
print eigvectors

[[ 0.06621482  0.0654548   0.0658585  ...,  0.00958088  0.00957642
   0.00973877]
 [-0.00970644 -0.01012571 -0.01043007 ...,  0.04045623  0.04124784
   0.04137731]
 [-0.05393686 -0.05974241 -0.05987509 ...,  0.02962554  0.03005097
   0.0306001 ]
 ..., 
 [-0.00440058  0.00934784 -0.02198565 ...,  0.00182746 -0.00472583
  -0.00436154]
 [-0.0013431  -0.00084383  0.00784515 ..., -0.00709422 -0.00594618
  -0.00106301]
 [-0.00358535  0.00257891  0.00325399 ...,  0.00494517 -0.00485391
   0.00266535]]


In [27]:
result['eigvalues']

array([  1.76459786e+02,   6.85218499e+01,   2.09509419e+01,
         1.29007349e+01,   7.02790929e+00,   5.63808597e+00,
         5.15381003e+00,   4.91827268e+00,   4.32874704e+00,
         4.06159555e+00,   3.96009941e+00,   3.83893598e+00,
         3.71302255e+00,   3.58059551e+00,   3.48479517e+00,
         3.33772387e+00,   3.23235779e+00,   3.12559334e+00,
         3.05668751e+00,   2.87537519e+00,   2.82583537e+00,
         2.71828038e+00,   2.65127046e+00,   2.51928562e+00,
         2.45815020e+00,   2.41443964e+00,   2.38693424e+00,
         2.35179329e+00,   2.31666826e+00,   2.21875896e+00,
         2.19978227e+00,   2.18514376e+00,   2.09326945e+00,
         2.08508029e+00,   2.07432732e+00,   1.99234275e+00,
         1.97883087e+00,   1.94209588e+00,   1.90257329e+00,
         1.89599980e+00,   1.83094056e+00,   1.80090794e+00,
         1.77619083e+00,   1.74505320e+00,   1.72544863e+00,
         1.69200549e+00,   1.68061539e+00,   1.64940066e+00,
         1.61948248e+00,

In [28]:
result['eigvectors']

array([[ 0.06621482, -0.00970644, -0.05393686, ..., -0.00440058,
        -0.0013431 , -0.00358535],
       [ 0.0654548 , -0.01012571, -0.05974241, ...,  0.00934784,
        -0.00084383,  0.00257891],
       [ 0.0658585 , -0.01043007, -0.05987509, ..., -0.02198565,
         0.00784515,  0.00325399],
       ..., 
       [ 0.06554835, -0.00117736, -0.07149946, ...,  0.03238418,
         0.03312268,  0.03492147],
       [ 0.06595858,  0.00010867, -0.07516464, ..., -0.06314162,
        -0.03389112, -0.00511459],
       [ 0.06604241,  0.00095407, -0.07738862, ...,  0.0850792 ,
         0.03349772, -0.03326779]])